import * as React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { useMovieSearch } from "../components/Search/useMovieSearch";
import { trpc } from "../utils/trpc";
import SearchResult from "../components/Search/SearchResult";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { movies } = useMovieSearch();
  const userQuery = trpc.user.all.useQuery();

  console.log(movies);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid grid-cols-1 gap-3 px-3 pt-10 md:grid-cols-2 md:gap-5 md:p-5 xl:grid-cols-3">
          {movies?.results?.map((movie: any) => (
            <SearchResult key={movie.id} movie={movie} />
          ))}
        </div>
      </main>
    </>
  );
}
